import { create } from 'zustand'
import { persist } from 'zustand/middleware'

// Outlook-style planner: per-child scheduled events with flexible time, optional
// recurrence ("apply to N days / weekdays / custom"), reminders, and free per-day
// notes. Reactive cache / local source of truth.

export type EventCategory =
  | 'school' | 'study' | 'homework' | 'activity' | 'sport' | 'music'
  | 'dance' | 'art' | 'coaching' | 'meal' | 'break' | 'free' | 'sleep' | 'other'

export type Repeat = 'none' | 'daily' | 'weekdays' | 'weekly' | 'custom'

export interface PlannerEvent {
  id: string
  childId: string
  title: string
  category: EventCategory
  date: string          // anchor date, yyyy-mm-dd
  startTime: string     // HH:mm
  endTime: string       // HH:mm
  location?: string
  notes?: string
  reminderMinutes?: number | null  // minutes before start; null/undefined = none
  repeat: Repeat
  repeatDays?: number[] // 0=Sun..6=Sat (for custom)
  repeatUntil?: string  // yyyy-mm-dd inclusive; '' = open-ended (capped on read)
  fromTimetable?: boolean // generated by the School Timetable builder (re-appliable)
  createdAt: number
}

export const CATEGORY_META: Record<EventCategory, { label: string; color: string; bg: string; icon: string }> = {
  school:   { label: 'School',        color: '#2563EB', bg: '#DBEAFE', icon: '🏫' },
  study:    { label: 'Self-study',    color: '#4F46E5', bg: '#E0E7FF', icon: '📚' },
  homework: { label: 'Homework',      color: '#7C3AED', bg: '#EDE9FE', icon: '📝' },
  activity: { label: 'Activity',      color: '#DB2777', bg: '#FCE7F3', icon: '⭐' },
  sport:    { label: 'Sport',         color: '#059669', bg: '#D1FAE5', icon: '🏅' },
  music:    { label: 'Music',         color: '#8B5CF6', bg: '#F3E8FF', icon: '🎵' },
  dance:    { label: 'Dance',         color: '#EC4899', bg: '#FCE7F3', icon: '💃' },
  art:      { label: 'Art',           color: '#F59E0B', bg: '#FEF3C7', icon: '🎨' },
  coaching: { label: 'Coaching',      color: '#0EA5E9', bg: '#E0F2FE', icon: '🧑‍🏫' },
  meal:     { label: 'Meal',          color: '#CA8A04', bg: '#FEF9C3', icon: '🍱' },
  break:    { label: 'Break',         color: '#64748B', bg: '#F1F5F9', icon: '☕' },
  free:     { label: 'Free time',     color: '#16A34A', bg: '#DCFCE7', icon: '🎮' },
  sleep:    { label: 'Sleep',         color: '#475569', bg: '#E2E8F0', icon: '😴' },
  other:    { label: 'Other',         color: '#6B7280', bg: '#F3F4F6', icon: '📌' },
}

interface PlannerState {
  events: Record<string, PlannerEvent>
  notes: Record<string, string>   // key `${childId}::${yyyy-mm-dd}` → note text
  _set: (e: PlannerEvent) => void
  _remove: (id: string) => void
  _removeMany: (ids: string[]) => void
  _setNote: (key: string, text: string) => void
  _bulk: (events: PlannerEvent[]) => void
}

export const usePlannerStore = create<PlannerState>()(
  persist(
    (set) => ({
      events: {},
      notes: {},
      _set: (e) => set((s) => ({ events: { ...s.events, [e.id]: e } })),
      _remove: (id) => set((s) => { const n = { ...s.events }; delete n[id]; return { events: n } }),
      _removeMany: (ids) => set((s) => { const n = { ...s.events }; ids.forEach(id => delete n[id]); return { events: n } }),
      _setNote: (key, text) => set((s) => ({ notes: { ...s.notes, [key]: text } })),
      _bulk: (events) => set((s) => {
        const next = { ...s.events }
        events.forEach(e => { next[e.id] = e })
        return { events: next }
      }),
    }),
    { name: 'mk-planner-v1' },
  ),
)

// ── date helpers ──────────────────────────────────────────────────────────────
export const ymd = (d: Date) => `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`
export const parseYmd = (s: string) => { const [y, m, d] = s.split('-').map(Number); return new Date(y, m - 1, d) }
export const noteKey = (childId: string, date: string) => `${childId}::${date}`
const sameDay = (a: Date, b: Date) => a.getFullYear() === b.getFullYear() && a.getMonth() === b.getMonth() && a.getDate() === b.getDate()
export const toMin = (t: string) => { const [h, m] = t.split(':').map(Number); return h * 60 + m }

/** Does a recurring (or one-off) event occur on the given calendar day? */
export function occursOn(e: PlannerEvent, day: Date): boolean {
  const anchor = parseYmd(e.date)
  const d0 = new Date(day.getFullYear(), day.getMonth(), day.getDate())
  const a0 = new Date(anchor.getFullYear(), anchor.getMonth(), anchor.getDate())
  if (d0 < a0) return false
  if (e.repeatUntil && d0 > parseYmd(e.repeatUntil)) return false
  const dow = d0.getDay()
  switch (e.repeat) {
    case 'none':     return sameDay(d0, a0)
    case 'daily':    return true
    case 'weekdays': return dow >= 1 && dow <= 5
    case 'weekly':   return dow === a0.getDay()
    case 'custom':   return (e.repeatDays ?? []).includes(dow)
    default:         return false
  }
}

export function eventsForChildOn(all: Record<string, PlannerEvent>, childId: string, day: Date): PlannerEvent[] {
  return Object.values(all)
    .filter(e => e.childId === childId && occursOn(e, day))
    .sort((a, b) => toMin(a.startTime) - toMin(b.startTime))
}

export function makeEventId() {
  return `evt-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`
}
